name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    # On utilise Ubuntu 22.04 pour garantir la compatibilité des outils de compilation
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libtinfo5 libncurses5
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.9
          buildozer-cmd: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secure-node-apk
          path: ./bin/*.apk