name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    # On force l'ancienne version d'Ubuntu pour avoir libtinfo5
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.9
          buildozer-cmd: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: secure-node-apk
          path: ./bin/*.apk